### ISSUE TITLE
Doesn't work on npp 7.2 (x32). What is the minimum npp version required for a plugin?

### ISSUE THREAD

**Issue by Baltazar500** [SinghRajenM/nppURLPlugin#3]
Doesn't work on npp 7.2 (x32). What is the minimum npp version required for a plugin? I get an error that MSVCP140.dll is missing and this popup :

>C:\Program Files (x86)\Notepad++\plugins\urlPlugin.dll
>---------------------------
>Не найден указанный модуль.
>
>urlPlugin.dll is not compatible with the current version of Notepad++.
>Do you want to remove this plugin from the plugins directory to prevent this message from the next launch?

**Comment by SinghRajenM** [comment]
Thanks for reporting the issue.
This issue is caused due to missing re-distrubutable of VS2015. Installing VS2015 re-distrubutable should fix the issue.

However, scintilla is updated in notepad++ v8.3.3.0 which introduced some interface changes too. Hence, we have upgraded the plugin too to v1.2.0.0. This version will work with notepad++ v8.3.3.0 onward.
